version: "3.8"
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3308:3308"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql