version: '3.7'

services:
  product-service-db:
    image: postgres:latest
    container_name: product-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product-service-db
    ports:
      - "5432:5432"
    volumes:
      - product-service-db-data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5433:80" 
    volumes:
      - pgadmin4-data:/var/lib/pgadmin4

  product-service:
    build: .
    container_name: product-service
    ports:
      - "8083:8080"
    depends_on:
      - product-service-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://product-service-db:5432/product-service-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  product-service-db-data:
  pgadmin4-data: