version: '3.8'
services:
  mysql:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: colle # Specify the name of the database you want to create
    ports:
      - "5434:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST : localhost
      MYSQL_PORT : 3306
      MYSQL_DB : cart
      MYSQL_USER : root
      MYSQL_PASSWORD : 
    ports:
      - "8084:8080"
    depends_on:
      - mysql
volumes:
  db_data:
    driver: local
