version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_database_username
      POSTGRES_PASSWORD: your_database_password
    ports:
      - "5434:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: cart_db
      POSTGRES_USER: cart_admim
      POSTGRES_PASSWORD: cart_password
    ports:
      - "8084:8080"
    depends_on:
      - postgres
