version: "4"
services:
  mysql:
    image: mysql:8.3.0
    container_name: payment-service-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    ports:
      - "3307:3306" # Mapping external port 3307 to internal port 3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  payment-service:
    image: payment-service
    container_name: payment-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/payment_service?useSSL=false # Use internal port 3306
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12345
